#include <map>
#include "AbilityFactory.h"
#include "Ability.h"
#include "AttackAbility.h"
#include "Enums.h"

std::map<AbilityId, Ability*> AbilityFactory::allAbilities;

void AbilityFactory::init()
{
    if (allAbilities.size() > 0)
        throw "Ability Factory has already been initialized."; // TODO: Exception class.


    // Pure Damage Abilities
    allAbilities.emplace(AbilityId::Cut, new AttackAbility(AbilityId::Cut, "Cut", "", Type::Normal, AbilityCategory::Physical, 50, 242, 30, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::DrillPeck, new AttackAbility(AbilityId::DrillPeck, "Drill Peck", "", Type::Flying, AbilityCategory::Physical, 80, 255, 20, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::EggBomb, new AttackAbility(AbilityId::EggBomb, "Egg Bomb", "", Type::Normal, AbilityCategory::Physical, 100, 191, 10, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::HornAttack, new AttackAbility(AbilityId::HornAttack, "Horn Attack", "", Type::Normal, AbilityCategory::Physical, 65, 255, 25, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::HydroPump, new AttackAbility(AbilityId::HydroPump, "Hydro Pump", "", Type::Water, AbilityCategory::Special, 110, 204, 5, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::MegaKick, new AttackAbility(AbilityId::MegaKick, "Mega Kick", "", Type::Normal, AbilityCategory::Physical, 120, 191, 5, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::MegaPunch, new AttackAbility(AbilityId::MegaPunch, "Mega Punch", "", Type::Normal, AbilityCategory::Physical, 80, 216, 20, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::PayDay, new AttackAbility(AbilityId::PayDay, "Pay Day", "A small amount of money is gained after the battle resolves.", Type::Normal, AbilityCategory::Physical, 40, 255, 20, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::Peck, new AttackAbility(AbilityId::Peck, "Peck", "", Type::Flying, AbilityCategory::Physical, 35, 255, 35, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::Pound, new AttackAbility(AbilityId::Pound, "Pound", "", Type::Normal, AbilityCategory::Physical, 40, 255, 35, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::RockThrow, new AttackAbility(AbilityId::RockThrow, "Rock Throw", "", Type::Rock, AbilityCategory::Physical, 50, 64.7, 15, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::Scratch, new AttackAbility(AbilityId::Scratch, "Scratch", "", Type::Normal, AbilityCategory::Physical, 40, 255, 35, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::Slam, new AttackAbility(AbilityId::Slam, "Slam", "", Type::Normal, AbilityCategory::Physical, 80, 191, 20, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::Strength, new AttackAbility(AbilityId::Strength, "Strength", "", Type::Normal, AbilityCategory::Physical, 80, 255, 15, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::Surf, new AttackAbility(AbilityId::Surf, "Surf", "Hits all adjacent Pokemon.", Type::Water, AbilityCategory::Special, 90, 255, 15, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::Tackle, new AttackAbility(AbilityId::Tackle, "Tackle", "", Type::Normal, AbilityCategory::Physical, 40, 242, 35, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::ViceGrip, new AttackAbility(AbilityId::ViceGrip, "Vice Grip", "", Type::Normal, AbilityCategory::Physical, 55, 255, 30, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::VineWhip, new AttackAbility(AbilityId::VineWhip, "Vine Whip", "", Type::Grass, AbilityCategory::Physical, 45, 255, 25, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::WaterGun, new AttackAbility(AbilityId::WaterGun, "Water Gun", "", Type::Water, AbilityCategory::Special, 40, 255, 25, 0, StatusEffect::None));
    allAbilities.emplace(AbilityId::WingAttack, new AttackAbility(AbilityId::WingAttack, "Wing Attack", "", Type::Flying, AbilityCategory::Physical, 60, 255, 35, 0, StatusEffect::None));

    return;
}

Ability* AbilityFactory::getAbility(const AbilityId &abilityId)
{
    if (allAbilities.count(abilityId) != 1)
        throw "Ability doesn't exist."; // TODO: Exception class.

    return allAbilities[abilityId];
}


std::map<PkmnId, std::vector<AbilityId>> AbilityFactory::learnSets{
    { PkmnId::Bulbasaur, { AbilityId::Growl, AbilityId::Tackle, AbilityId::LeechSeed, AbilityId::VineWhip, AbilityId::PoisonPowder, AbilityId::RazorLeaf, AbilityId::Growth, AbilityId::SleepPowder, AbilityId::SolarBeam, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute } },
    { PkmnId::Ivysaur, { AbilityId::Growl, AbilityId::LeechSeed, AbilityId::Tackle, AbilityId::VineWhip, AbilityId::PoisonPowder, AbilityId::RazorLeaf, AbilityId::Growth, AbilityId::SleepPowder, AbilityId::SolarBeam, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Venusaur, { AbilityId::Growl, AbilityId::LeechSeed, AbilityId::Tackle, AbilityId::VineWhip, AbilityId::PoisonPowder, AbilityId::RazorLeaf, AbilityId::Growth, AbilityId::SleepPowder, AbilityId::SolarBeam, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Charmander, { AbilityId::Growl, AbilityId::Scratch, AbilityId::Ember, AbilityId::Leer, AbilityId::Rage, AbilityId::Slash, AbilityId::Flamethrower, AbilityId::FireSpin, AbilityId::Cut, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::SwordsDance, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::DragonRage, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Charmeleon, { AbilityId::Ember, AbilityId::Growl, AbilityId::Scratch, AbilityId::Leer, AbilityId::Rage, AbilityId::Slash, AbilityId::Flamethrower, AbilityId::FireSpin, AbilityId::Cut, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::SwordsDance, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::DragonRage, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Charizard, { AbilityId::Ember, AbilityId::Growl, AbilityId::Leer, AbilityId::Scratch, AbilityId::Rage, AbilityId::Slash, AbilityId::Flamethrower, AbilityId::FireSpin, AbilityId::Cut, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::SwordsDance, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::DragonRage, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::Fly} },
    { PkmnId::Squirtle, { AbilityId::Tackle, AbilityId::TailWhip, AbilityId::Bubble, AbilityId::WaterGun, AbilityId::Bite, AbilityId::Withdraw, AbilityId::SkullBash, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Wartortle, { AbilityId::Bubble, AbilityId::Tackle, AbilityId::TailWhip, AbilityId::WaterGun, AbilityId::Bite, AbilityId::Withdraw, AbilityId::SkullBash, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Blastoise, { AbilityId::Bubble, AbilityId::Tackle, AbilityId::TailWhip, AbilityId::WaterGun, AbilityId::Bite, AbilityId::Withdraw, AbilityId::SkullBash, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Caterpie, { AbilityId::StringShot, AbilityId::Tackle} },
    { PkmnId::Metapod, { AbilityId::Harden, AbilityId::StringShot, AbilityId::Tackle} },
    { PkmnId::Butterfree, { AbilityId::Confusion, AbilityId::PoisonPowder, AbilityId::StunSpore, AbilityId::SleepPowder, AbilityId::Supersonic, AbilityId::Whirlwind, AbilityId::Psybeam, AbilityId::Harden, AbilityId::StringShot, AbilityId::Tackle, AbilityId::RazorWind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::SolarBeam, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::Rest, AbilityId::Psywave, AbilityId::Substitute, AbilityId::Gust, AbilityId::Flash} },
    { PkmnId::Weedle, { AbilityId::PoisonSting, AbilityId::StringShot} },
    { PkmnId::Kakuna, { AbilityId::Harden, AbilityId::PoisonSting, AbilityId::StringShot} },
    { PkmnId::Beedrill, { AbilityId::FuryAttack, AbilityId::FocusEnergy, AbilityId::Twineedle, AbilityId::Rage, AbilityId::PinMissile, AbilityId::Agility, AbilityId::Harden, AbilityId::PoisonSting, AbilityId::StringShot, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::MegaDrain, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Pidgey, { AbilityId::Gust, AbilityId::SandAttack, AbilityId::QuickAttack, AbilityId::Whirlwind, AbilityId::WingAttack, AbilityId::Agility, AbilityId::MirrorMove, AbilityId::Fly, AbilityId::RazorWind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::SkyAttack, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Pidgeotto, { AbilityId::Gust, AbilityId::SandAttack, AbilityId::QuickAttack, AbilityId::Whirlwind, AbilityId::WingAttack, AbilityId::Agility, AbilityId::MirrorMove, AbilityId::Fly, AbilityId::RazorWind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::SkyAttack, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Pidgeot, { AbilityId::Gust, AbilityId::QuickAttack, AbilityId::SandAttack, AbilityId::Whirlwind, AbilityId::WingAttack, AbilityId::Agility, AbilityId::MirrorMove, AbilityId::Fly, AbilityId::RazorWind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::SkyAttack, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Rattata, { AbilityId::Tackle, AbilityId::TailWhip, AbilityId::QuickAttack, AbilityId::HyperFang, AbilityId::FocusEnergy, AbilityId::SuperFang, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Raticate, { AbilityId::QuickAttack, AbilityId::Tackle, AbilityId::TailWhip, AbilityId::HyperFang, AbilityId::FocusEnergy, AbilityId::SuperFang, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Spearow, { AbilityId::Growl, AbilityId::Peck, AbilityId::Leer, AbilityId::FuryAttack, AbilityId::MirrorMove, AbilityId::DrillPeck, AbilityId::Agility, AbilityId::Fly, AbilityId::RazorWind, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkyAttack, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Fearow, { AbilityId::Growl, AbilityId::Leer, AbilityId::Peck, AbilityId::FuryAttack, AbilityId::MirrorMove, AbilityId::DrillPeck, AbilityId::Agility, AbilityId::Fly, AbilityId::RazorWind, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkyAttack, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Ekans, { AbilityId::Leer, AbilityId::Wrap, AbilityId::PoisonSting, AbilityId::Bite, AbilityId::Glare, AbilityId::Screech, AbilityId::Acid, AbilityId::Strength, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Arbok, { AbilityId::Leer, AbilityId::PoisonSting, AbilityId::Wrap, AbilityId::Bite, AbilityId::Glare, AbilityId::Screech, AbilityId::Acid, AbilityId::Strength, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Pikachu, { AbilityId::Growl, AbilityId::ThunderShock, AbilityId::ThunderWave, AbilityId::QuickAttack, AbilityId::Swift, AbilityId::Agility, AbilityId::Thunder, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::PayDay, AbilityId::Submission, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::TailWhip, AbilityId::Slam, AbilityId::LightScreen} },
    { PkmnId::Raichu, { AbilityId::Growl, AbilityId::ThunderShock, AbilityId::ThunderWave, AbilityId::Agility, AbilityId::QuickAttack, AbilityId::Swift, AbilityId::Thunder, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::PayDay, AbilityId::Submission, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::LightScreen, AbilityId::Slam, AbilityId::TailWhip} },
    { PkmnId::Sandshrew, { AbilityId::Scratch, AbilityId::SandAttack, AbilityId::Slash, AbilityId::PoisonSting, AbilityId::Swift, AbilityId::FurySwipes, AbilityId::Cut, AbilityId::Strength, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Submission, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Sandslash, { AbilityId::SandAttack, AbilityId::Scratch, AbilityId::Slash, AbilityId::PoisonSting, AbilityId::Swift, AbilityId::FurySwipes, AbilityId::Cut, AbilityId::Strength, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Nidorana, { AbilityId::Growl, AbilityId::Tackle, AbilityId::Scratch, AbilityId::PoisonSting, AbilityId::TailWhip, AbilityId::Bite, AbilityId::FurySwipes, AbilityId::DoubleKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Nidorina, { AbilityId::Growl, AbilityId::Scratch, AbilityId::Tackle, AbilityId::PoisonSting, AbilityId::TailWhip, AbilityId::Bite, AbilityId::FurySwipes, AbilityId::DoubleKick, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Nidoqueen, { AbilityId::BodySlam, AbilityId::Scratch, AbilityId::Tackle, AbilityId::TailWhip, AbilityId::PoisonSting, AbilityId::Bite, AbilityId::DoubleKick, AbilityId::FurySwipes, AbilityId::Growl, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::PayDay, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Nidorano, { AbilityId::Leer, AbilityId::Tackle, AbilityId::HornAttack, AbilityId::PoisonSting, AbilityId::FocusEnergy, AbilityId::FuryAttack, AbilityId::HornDrill, AbilityId::DoubleKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Nidorino, { AbilityId::HornAttack, AbilityId::Leer, AbilityId::Tackle, AbilityId::PoisonSting, AbilityId::FocusEnergy, AbilityId::FuryAttack, AbilityId::HornDrill, AbilityId::DoubleKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Nidoking, { AbilityId::HornAttack, AbilityId::PoisonSting, AbilityId::Tackle, AbilityId::Thrash, AbilityId::DoubleKick, AbilityId::FocusEnergy, AbilityId::FuryAttack, AbilityId::HornDrill, AbilityId::Leer, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::PayDay, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Clefairy, { AbilityId::Growl, AbilityId::Pound, AbilityId::Sing, AbilityId::DoubleSlap, AbilityId::Minimize, AbilityId::Metronome, AbilityId::DefenseCurl, AbilityId::LightScreen, AbilityId::Strength, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::SolarBeam, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Clefable, { AbilityId::DoubleSlap, AbilityId::Metronome, AbilityId::Minimize, AbilityId::Sing, AbilityId::DefenseCurl, AbilityId::Growl, AbilityId::LightScreen, AbilityId::Pound, AbilityId::Strength, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::SolarBeam, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Vulpix, { AbilityId::Ember, AbilityId::TailWhip, AbilityId::QuickAttack, AbilityId::Roar, AbilityId::ConfuseRay, AbilityId::Flamethrower, AbilityId::FireSpin, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Ninetales, { AbilityId::Ember, AbilityId::QuickAttack, AbilityId::Roar, AbilityId::TailWhip, AbilityId::ConfuseRay, AbilityId::FireSpin, AbilityId::Flamethrower, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Jigglypuff, { AbilityId::Sing, AbilityId::Pound, AbilityId::Disable, AbilityId::DefenseCurl, AbilityId::DoubleSlap, AbilityId::Rest, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::Strength, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::SolarBeam, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Wigglytuff, { AbilityId::DefenseCurl, AbilityId::Disable, AbilityId::DoubleSlap, AbilityId::Sing, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::Pound, AbilityId::Rest, AbilityId::Strength, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::SolarBeam, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Zubat, { AbilityId::LeechLife, AbilityId::Supersonic, AbilityId::Bite, AbilityId::ConfuseRay, AbilityId::WingAttack, AbilityId::Haze, AbilityId::RazorWind, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Golbat, { AbilityId::Bite, AbilityId::LeechLife, AbilityId::Screech, AbilityId::Supersonic, AbilityId::ConfuseRay, AbilityId::WingAttack, AbilityId::Haze, AbilityId::RazorWind, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Oddish, { AbilityId::Absorb, AbilityId::PoisonPowder, AbilityId::StunSpore, AbilityId::SleepPowder, AbilityId::Acid, AbilityId::PetalDance, AbilityId::SolarBeam, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Gloom, { AbilityId::Absorb, AbilityId::PoisonPowder, AbilityId::StunSpore, AbilityId::SleepPowder, AbilityId::Acid, AbilityId::PetalDance, AbilityId::SolarBeam, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Vileplume, { AbilityId::Acid, AbilityId::PetalDance, AbilityId::SleepPowder, AbilityId::StunSpore, AbilityId::PoisonPowder, AbilityId::Absorb, AbilityId::SolarBeam, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Paras, { AbilityId::Scratch, AbilityId::StunSpore, AbilityId::LeechLife, AbilityId::Spore, AbilityId::Slash, AbilityId::Growth, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::SolarBeam, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Parasect, { AbilityId::LeechLife, AbilityId::Scratch, AbilityId::StunSpore, AbilityId::Spore, AbilityId::Slash, AbilityId::Growth, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::SolarBeam, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Venonat, { AbilityId::Disable, AbilityId::Tackle, AbilityId::PoisonPowder, AbilityId::LeechLife, AbilityId::StunSpore, AbilityId::Psybeam, AbilityId::SleepPowder, AbilityId::Psychic, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::SolarBeam, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Psywave, AbilityId::Substitute, AbilityId::Supersonic, AbilityId::Confusion, AbilityId::Flash} },
    { PkmnId::Venomoth, { AbilityId::Disable, AbilityId::LeechLife, AbilityId::PoisonPowder, AbilityId::Tackle, AbilityId::StunSpore, AbilityId::Psybeam, AbilityId::SleepPowder, AbilityId::Psychic, AbilityId::RazorWind, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::SolarBeam, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::Rest, AbilityId::Psywave, AbilityId::Substitute, AbilityId::Confusion, AbilityId::Supersonic, AbilityId::Flash} },
    { PkmnId::Diglett, { AbilityId::Scratch, AbilityId::Growl, AbilityId::Dig, AbilityId::SandAttack, AbilityId::Slash, AbilityId::Earthquake, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::Fissure, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute, AbilityId::Cut} },
    { PkmnId::Dugtrio, { AbilityId::Dig, AbilityId::Growl, AbilityId::Scratch, AbilityId::SandAttack, AbilityId::Slash, AbilityId::Earthquake, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Fissure, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute, AbilityId::Cut} },
    { PkmnId::Meowth, { AbilityId::Growl, AbilityId::Scratch, AbilityId::Bite, AbilityId::PayDay, AbilityId::Screech, AbilityId::FurySwipes, AbilityId::Slash, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Persian, { AbilityId::Bite, AbilityId::Growl, AbilityId::Scratch, AbilityId::Screech, AbilityId::PayDay, AbilityId::FurySwipes, AbilityId::Slash, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Psyduck, { AbilityId::Scratch, AbilityId::TailWhip, AbilityId::Disable, AbilityId::Confusion, AbilityId::FurySwipes, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::PayDay, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Golduck, { AbilityId::Disable, AbilityId::Scratch, AbilityId::TailWhip, AbilityId::Confusion, AbilityId::FurySwipes, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::PayDay, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Mankey, { AbilityId::Leer, AbilityId::Scratch, AbilityId::KarateChop, AbilityId::FurySwipes, AbilityId::FocusEnergy, AbilityId::SeismicToss, AbilityId::Thrash, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::PayDay, AbilityId::Submission, AbilityId::Counter, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute, AbilityId::LowKick, AbilityId::Screech} },
    { PkmnId::Primeape, { AbilityId::FurySwipes, AbilityId::KarateChop, AbilityId::Leer, AbilityId::Scratch, AbilityId::FocusEnergy, AbilityId::SeismicToss, AbilityId::Thrash, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::PayDay, AbilityId::Submission, AbilityId::Counter, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute, AbilityId::LowKick, AbilityId::Screech} },
    { PkmnId::Growlithe, { AbilityId::Bite, AbilityId::Roar, AbilityId::Ember, AbilityId::Leer, AbilityId::TakeDown, AbilityId::Agility, AbilityId::Flamethrower, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::DragonRage, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Arcanine, { AbilityId::Ember, AbilityId::Leer, AbilityId::Roar, AbilityId::TakeDown, AbilityId::Agility, AbilityId::Bite, AbilityId::Flamethrower, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::DragonRage, AbilityId::Dig, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Poliwag, { AbilityId::Bubble, AbilityId::Hypnosis, AbilityId::WaterGun, AbilityId::DoubleSlap, AbilityId::BodySlam, AbilityId::Amnesia, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Psychic, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Psywave, AbilityId::Substitute} },
    { PkmnId::Poliwhirl, { AbilityId::Bubble, AbilityId::Hypnosis, AbilityId::WaterGun, AbilityId::DoubleSlap, AbilityId::BodySlam, AbilityId::Amnesia, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Psychic, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Psywave, AbilityId::Substitute} },
    { PkmnId::Poliwrath, { AbilityId::BodySlam, AbilityId::DoubleSlap, AbilityId::Hypnosis, AbilityId::WaterGun, AbilityId::Amnesia, AbilityId::Bubble, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Psychic, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Psywave, AbilityId::Substitute} },
    { PkmnId::Abra, { AbilityId::Teleport, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Psychic, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Metronome, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Kadabra, { AbilityId::Confusion, AbilityId::Disable, AbilityId::Teleport, AbilityId::Psybeam, AbilityId::Recover, AbilityId::Psychic, AbilityId::Reflect, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute, AbilityId::Kinesis} },
    { PkmnId::Alakazam, { AbilityId::Confusion, AbilityId::Disable, AbilityId::Teleport, AbilityId::Psybeam, AbilityId::Recover, AbilityId::Psychic, AbilityId::Reflect, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute, AbilityId::Kinesis} },
    { PkmnId::Machop, { AbilityId::KarateChop, AbilityId::LowKick, AbilityId::Leer, AbilityId::FocusEnergy, AbilityId::SeismicToss, AbilityId::Submission, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Counter, AbilityId::Rage, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Machoke, { AbilityId::KarateChop, AbilityId::Leer, AbilityId::LowKick, AbilityId::FocusEnergy, AbilityId::SeismicToss, AbilityId::Submission, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Counter, AbilityId::Rage, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Machamp, { AbilityId::KarateChop, AbilityId::Leer, AbilityId::LowKick, AbilityId::FocusEnergy, AbilityId::SeismicToss, AbilityId::Submission, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Counter, AbilityId::Rage, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Bellsprout, { AbilityId::Growth, AbilityId::VineWhip, AbilityId::Wrap, AbilityId::PoisonPowder, AbilityId::SleepPowder, AbilityId::StunSpore, AbilityId::Acid, AbilityId::RazorLeaf, AbilityId::Slam, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::SolarBeam, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Weepinbell, { AbilityId::Growth, AbilityId::VineWhip, AbilityId::Wrap, AbilityId::PoisonPowder, AbilityId::SleepPowder, AbilityId::StunSpore, AbilityId::Acid, AbilityId::RazorLeaf, AbilityId::Slam, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::SolarBeam, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Victreebel, { AbilityId::Acid, AbilityId::RazorLeaf, AbilityId::SleepPowder, AbilityId::StunSpore, AbilityId::Wrap, AbilityId::PoisonPowder, AbilityId::Growth, AbilityId::Slam, AbilityId::VineWhip, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::SolarBeam, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Tentacool, { AbilityId::Acid, AbilityId::Supersonic, AbilityId::Wrap, AbilityId::PoisonSting, AbilityId::WaterGun, AbilityId::Constrict, AbilityId::Barrier, AbilityId::Screech, AbilityId::HydroPump, AbilityId::Cut, AbilityId::Surf, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Tentacruel, { AbilityId::Acid, AbilityId::Supersonic, AbilityId::Wrap, AbilityId::PoisonSting, AbilityId::WaterGun, AbilityId::Constrict, AbilityId::Barrier, AbilityId::Screech, AbilityId::HydroPump, AbilityId::Cut, AbilityId::Surf, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Geodude, { AbilityId::Tackle, AbilityId::DefenseCurl, AbilityId::RockThrow, AbilityId::SelfDestruct, AbilityId::Harden, AbilityId::Earthquake, AbilityId::Explosion, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::FireBlast, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Graveler, { AbilityId::DefenseCurl, AbilityId::Tackle, AbilityId::RockThrow, AbilityId::SelfDestruct, AbilityId::Harden, AbilityId::Earthquake, AbilityId::Explosion, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::FireBlast, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Golem, { AbilityId::DefenseCurl, AbilityId::Tackle, AbilityId::RockThrow, AbilityId::SelfDestruct, AbilityId::Harden, AbilityId::Earthquake, AbilityId::Explosion, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::FireBlast, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Ponyta, { AbilityId::Ember, AbilityId::TailWhip, AbilityId::Stomp, AbilityId::Growl, AbilityId::FireSpin, AbilityId::TakeDown, AbilityId::Agility, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Rapidash, { AbilityId::Ember, AbilityId::Growl, AbilityId::Stomp, AbilityId::TailWhip, AbilityId::FireSpin, AbilityId::TakeDown, AbilityId::Agility, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Slowpoke, { AbilityId::Confusion, AbilityId::Disable, AbilityId::Headbutt, AbilityId::Growl, AbilityId::WaterGun, AbilityId::Amnesia, AbilityId::Psychic, AbilityId::Surf, AbilityId::Strength, AbilityId::Flash, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::PayDay, AbilityId::Rage, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Slowbro, { AbilityId::Confusion, AbilityId::Disable, AbilityId::Headbutt, AbilityId::Growl, AbilityId::WaterGun, AbilityId::Withdraw, AbilityId::Amnesia, AbilityId::Psychic, AbilityId::Surf, AbilityId::Strength, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::PayDay, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Magnemite, { AbilityId::Tackle, AbilityId::SonicBoom, AbilityId::ThunderShock, AbilityId::Supersonic, AbilityId::ThunderWave, AbilityId::Swift, AbilityId::Screech, AbilityId::Flash, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Magneton, { AbilityId::SonicBoom, AbilityId::Tackle, AbilityId::ThunderShock, AbilityId::Supersonic, AbilityId::ThunderWave, AbilityId::Swift, AbilityId::Screech, AbilityId::Flash, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Farfetchd, { AbilityId::Peck, AbilityId::SandAttack, AbilityId::Leer, AbilityId::FuryAttack, AbilityId::SwordsDance, AbilityId::Agility, AbilityId::Slash, AbilityId::Cut, AbilityId::Fly, AbilityId::RazorWind, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Doduo, { AbilityId::Peck, AbilityId::Growl, AbilityId::FuryAttack, AbilityId::DrillPeck, AbilityId::Rage, AbilityId::TriAttack, AbilityId::Agility, AbilityId::Fly, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::SkyAttack, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Dodrio, { AbilityId::FuryAttack, AbilityId::Growl, AbilityId::Peck, AbilityId::DrillPeck, AbilityId::Rage, AbilityId::TriAttack, AbilityId::Agility, AbilityId::Fly, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::SkyAttack, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Seel, { AbilityId::Headbutt, AbilityId::Growl, AbilityId::AuroraBeam, AbilityId::Rest, AbilityId::TakeDown, AbilityId::IceBeam, AbilityId::Surf, AbilityId::Strength, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::Blizzard, AbilityId::PayDay, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Substitute} },
    { PkmnId::Dewgong, { AbilityId::AuroraBeam, AbilityId::Growl, AbilityId::Headbutt, AbilityId::Rest, AbilityId::TakeDown, AbilityId::IceBeam, AbilityId::Surf, AbilityId::Strength, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::PayDay, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Substitute} },
    { PkmnId::Grimer, { AbilityId::Disable, AbilityId::Pound, AbilityId::PoisonGas, AbilityId::Minimize, AbilityId::Sludge, AbilityId::Harden, AbilityId::Screech, AbilityId::AcidArmor, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SelfDestruct, AbilityId::FireBlast, AbilityId::Rest, AbilityId::Explosion, AbilityId::Substitute} },
    { PkmnId::Muk, { AbilityId::Disable, AbilityId::PoisonGas, AbilityId::Pound, AbilityId::Minimize, AbilityId::Sludge, AbilityId::Harden, AbilityId::Screech, AbilityId::AcidArmor, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SelfDestruct, AbilityId::FireBlast, AbilityId::Rest, AbilityId::Explosion, AbilityId::Substitute} },
    { PkmnId::Shellder, { AbilityId::Tackle, AbilityId::Withdraw, AbilityId::Supersonic, AbilityId::Clamp, AbilityId::AuroraBeam, AbilityId::Leer, AbilityId::IceBeam, AbilityId::Surf, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SelfDestruct, AbilityId::Swift, AbilityId::Rest, AbilityId::Explosion, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Cloyster, { AbilityId::AuroraBeam, AbilityId::Clamp, AbilityId::Supersonic, AbilityId::Withdraw, AbilityId::SpikeCannon, AbilityId::IceBeam, AbilityId::Leer, AbilityId::Tackle, AbilityId::Surf, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SelfDestruct, AbilityId::Swift, AbilityId::Rest, AbilityId::Explosion, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Gastly, { AbilityId::ConfuseRay, AbilityId::Lick, AbilityId::NightShade, AbilityId::Hypnosis, AbilityId::DreamEater, AbilityId::Toxic, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SelfDestruct, AbilityId::Rest, AbilityId::Psywave, AbilityId::Explosion, AbilityId::Substitute} },
    { PkmnId::Haunter, { AbilityId::ConfuseRay, AbilityId::Lick, AbilityId::NightShade, AbilityId::Hypnosis, AbilityId::DreamEater, AbilityId::Toxic, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SelfDestruct, AbilityId::Rest, AbilityId::Psywave, AbilityId::Explosion, AbilityId::Substitute} },
    { PkmnId::Gengar, { AbilityId::ConfuseRay, AbilityId::Lick, AbilityId::NightShade, AbilityId::Hypnosis, AbilityId::DreamEater, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::SelfDestruct, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Psywave, AbilityId::Explosion, AbilityId::Substitute} },
    { PkmnId::Onix, { AbilityId::Screech, AbilityId::Tackle, AbilityId::Bind, AbilityId::RockThrow, AbilityId::Rage, AbilityId::Slam, AbilityId::Harden, AbilityId::Strength, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SelfDestruct, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Explosion, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Drowzee, { AbilityId::Hypnosis, AbilityId::Pound, AbilityId::Disable, AbilityId::Confusion, AbilityId::Headbutt, AbilityId::PoisonGas, AbilityId::Psychic, AbilityId::Meditate, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Metronome, AbilityId::SkullBash, AbilityId::DreamEater, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Hypno, { AbilityId::Confusion, AbilityId::Disable, AbilityId::Hypnosis, AbilityId::Pound, AbilityId::Headbutt, AbilityId::PoisonGas, AbilityId::Psychic, AbilityId::Meditate, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Metronome, AbilityId::SkullBash, AbilityId::DreamEater, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Krabby, { AbilityId::Bubble, AbilityId::Leer, AbilityId::ViceGrip, AbilityId::Guillotine, AbilityId::Stomp, AbilityId::Crabhammer, AbilityId::Harden, AbilityId::Cut, AbilityId::Surf, AbilityId::Strength, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Kingler, { AbilityId::Bubble, AbilityId::Leer, AbilityId::ViceGrip, AbilityId::Guillotine, AbilityId::Stomp, AbilityId::Crabhammer, AbilityId::Harden, AbilityId::Cut, AbilityId::Surf, AbilityId::Strength, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Voltorb, { AbilityId::Screech, AbilityId::Tackle, AbilityId::SonicBoom, AbilityId::SelfDestruct, AbilityId::LightScreen, AbilityId::Swift, AbilityId::Explosion, AbilityId::Flash, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Substitute} },
    { PkmnId::Electrode, { AbilityId::Screech, AbilityId::SonicBoom, AbilityId::Tackle, AbilityId::SelfDestruct, AbilityId::LightScreen, AbilityId::Swift, AbilityId::Explosion, AbilityId::Flash, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Substitute} },
    { PkmnId::Exeggcute, { AbilityId::Barrage, AbilityId::Hypnosis, AbilityId::Reflect, AbilityId::LeechSeed, AbilityId::StunSpore, AbilityId::PoisonPowder, AbilityId::SolarBeam, AbilityId::SleepPowder, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SelfDestruct, AbilityId::EggBomb, AbilityId::Rest, AbilityId::Psywave, AbilityId::Explosion, AbilityId::Substitute} },
    { PkmnId::Exeggutor, { AbilityId::Barrage, AbilityId::Hypnosis, AbilityId::Stomp, AbilityId::LeechSeed, AbilityId::PoisonPowder, AbilityId::Reflect, AbilityId::SleepPowder, AbilityId::SolarBeam, AbilityId::StunSpore, AbilityId::Strength, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SelfDestruct, AbilityId::EggBomb, AbilityId::Rest, AbilityId::Psywave, AbilityId::Explosion, AbilityId::Substitute} },
    { PkmnId::Cubone, { AbilityId::BoneClub, AbilityId::Growl, AbilityId::Leer, AbilityId::FocusEnergy, AbilityId::Thrash, AbilityId::Bonemerang, AbilityId::Rage, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::TailWhip, AbilityId::Headbutt} },
    { PkmnId::Marowak, { AbilityId::BoneClub, AbilityId::FocusEnergy, AbilityId::Growl, AbilityId::Leer, AbilityId::Thrash, AbilityId::Bonemerang, AbilityId::Rage, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::TailWhip, AbilityId::Headbutt} },
    { PkmnId::Hitmonlee, { AbilityId::DoubleKick, AbilityId::Meditate, AbilityId::RollingKick, AbilityId::JumpKick, AbilityId::FocusEnergy, AbilityId::HighJumpKick, AbilityId::MegaKick, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Hitmonchan, { AbilityId::Agility, AbilityId::CometPunch, AbilityId::FirePunch, AbilityId::IcePunch, AbilityId::ThunderPunch, AbilityId::MegaPunch, AbilityId::Counter, AbilityId::Strength, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::Submission, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Lickitung, { AbilityId::Supersonic, AbilityId::Wrap, AbilityId::Stomp, AbilityId::Disable, AbilityId::DefenseCurl, AbilityId::Slam, AbilityId::Screech, AbilityId::Cut, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::SwordsDance, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Koffing, { AbilityId::Smog, AbilityId::Tackle, AbilityId::Sludge, AbilityId::Smokescreen, AbilityId::SelfDestruct, AbilityId::Haze, AbilityId::Explosion, AbilityId::Toxic, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Weezing, { AbilityId::Sludge, AbilityId::Smog, AbilityId::Tackle, AbilityId::Smokescreen, AbilityId::SelfDestruct, AbilityId::Haze, AbilityId::Explosion, AbilityId::Toxic, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Rhyhorn, { AbilityId::HornAttack, AbilityId::Stomp, AbilityId::TailWhip, AbilityId::FuryAttack, AbilityId::HornDrill, AbilityId::Leer, AbilityId::TakeDown, AbilityId::Strength, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Rhydon, { AbilityId::FuryAttack, AbilityId::HornAttack, AbilityId::Stomp, AbilityId::TailWhip, AbilityId::HornDrill, AbilityId::Leer, AbilityId::TakeDown, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::PayDay, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Chansey, { AbilityId::DoubleSlap, AbilityId::Pound, AbilityId::Sing, AbilityId::Growl, AbilityId::Minimize, AbilityId::DefenseCurl, AbilityId::LightScreen, AbilityId::DoubleEdge, AbilityId::Strength, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::SolarBeam, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Metronome, AbilityId::EggBomb, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::SoftBoiled, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute, AbilityId::TailWhip} },
    { PkmnId::Tangela, { AbilityId::Bind, AbilityId::Constrict, AbilityId::Absorb, AbilityId::PoisonPowder, AbilityId::StunSpore, AbilityId::SleepPowder, AbilityId::Slam, AbilityId::Growth, AbilityId::Cut, AbilityId::SwordsDance, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::SolarBeam, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::VineWhip} },
    { PkmnId::Kangaskhan, { AbilityId::CometPunch, AbilityId::Rage, AbilityId::Bite, AbilityId::TailWhip, AbilityId::MegaPunch, AbilityId::Leer, AbilityId::DizzyPunch, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Horsea, { AbilityId::Bubble, AbilityId::Smokescreen, AbilityId::Leer, AbilityId::WaterGun, AbilityId::Agility, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Seadra, { AbilityId::Bubble, AbilityId::Smokescreen, AbilityId::Leer, AbilityId::WaterGun, AbilityId::Agility, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Goldeen, { AbilityId::Peck, AbilityId::TailWhip, AbilityId::Supersonic, AbilityId::HornAttack, AbilityId::FuryAttack, AbilityId::Waterfall, AbilityId::HornDrill, AbilityId::Agility, AbilityId::Surf, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Seaking, { AbilityId::Peck, AbilityId::Supersonic, AbilityId::TailWhip, AbilityId::HornAttack, AbilityId::FuryAttack, AbilityId::Waterfall, AbilityId::HornDrill, AbilityId::Agility, AbilityId::Surf, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Staryu, { AbilityId::Tackle, AbilityId::WaterGun, AbilityId::Harden, AbilityId::Recover, AbilityId::Swift, AbilityId::Minimize, AbilityId::LightScreen, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Flash, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Starmie, { AbilityId::Harden, AbilityId::Tackle, AbilityId::WaterGun, AbilityId::HydroPump, AbilityId::LightScreen, AbilityId::Minimize, AbilityId::Recover, AbilityId::Swift, AbilityId::Surf, AbilityId::Flash, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::MrMime, { AbilityId::Barrier, AbilityId::Confusion, AbilityId::LightScreen, AbilityId::DoubleSlap, AbilityId::Meditate, AbilityId::Substitute, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::SolarBeam, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Metronome, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave} },
    { PkmnId::Scyther, { AbilityId::QuickAttack, AbilityId::Leer, AbilityId::FocusEnergy, AbilityId::DoubleTeam, AbilityId::Slash, AbilityId::SwordsDance, AbilityId::Agility, AbilityId::Cut, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Mimic, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::WingAttack} },
    { PkmnId::Jynx, { AbilityId::LovelyKiss, AbilityId::Pound, AbilityId::Lick, AbilityId::DoubleSlap, AbilityId::IcePunch, AbilityId::BodySlam, AbilityId::Thrash, AbilityId::Blizzard, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Metronome, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Psywave, AbilityId::Substitute} },
    { PkmnId::Electabuzz, { AbilityId::Leer, AbilityId::QuickAttack, AbilityId::ThunderShock, AbilityId::Screech, AbilityId::ThunderPunch, AbilityId::LightScreen, AbilityId::Thunder, AbilityId::Strength, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Metronome, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::Substitute} },
    { PkmnId::Magmar, { AbilityId::Ember, AbilityId::Leer, AbilityId::ConfuseRay, AbilityId::FirePunch, AbilityId::Smokescreen, AbilityId::Smog, AbilityId::Flamethrower, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Metronome, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Psywave, AbilityId::Substitute} },
    { PkmnId::Pinsir, { AbilityId::ViceGrip, AbilityId::SeismicToss, AbilityId::Guillotine, AbilityId::FocusEnergy, AbilityId::Harden, AbilityId::Slash, AbilityId::SwordsDance, AbilityId::Cut, AbilityId::Strength, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute, AbilityId::Bind} },
    { PkmnId::Tauros, { AbilityId::Tackle, AbilityId::Stomp, AbilityId::TailWhip, AbilityId::Leer, AbilityId::Rage, AbilityId::TakeDown, AbilityId::Strength, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Magikarp, { AbilityId::Splash, AbilityId::Tackle} },
    { PkmnId::Gyarados, { AbilityId::Bite, AbilityId::DragonRage, AbilityId::HydroPump, AbilityId::Leer, AbilityId::HyperBeam, AbilityId::Splash, AbilityId::Tackle, AbilityId::Surf, AbilityId::Strength, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Lapras, { AbilityId::Growl, AbilityId::WaterGun, AbilityId::Sing, AbilityId::Mist, AbilityId::BodySlam, AbilityId::ConfuseRay, AbilityId::IceBeam, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Strength, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::SolarBeam, AbilityId::DragonRage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Psywave, AbilityId::Substitute} },
    { PkmnId::Ditto, { AbilityId::Transform} },
    { PkmnId::Eevee, { AbilityId::SandAttack, AbilityId::Tackle, AbilityId::QuickAttack, AbilityId::TailWhip, AbilityId::Bite, AbilityId::TakeDown, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::Growl, AbilityId::FocusEnergy} },
    { PkmnId::Vaporeon, { AbilityId::QuickAttack, AbilityId::SandAttack, AbilityId::Tackle, AbilityId::WaterGun, AbilityId::TailWhip, AbilityId::Bite, AbilityId::AcidArmor, AbilityId::Haze, AbilityId::Mist, AbilityId::HydroPump, AbilityId::TakeDown, AbilityId::Surf, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::AuroraBeam, AbilityId::FocusEnergy, AbilityId::Growl} },
    { PkmnId::Jolteon, { AbilityId::QuickAttack, AbilityId::SandAttack, AbilityId::Tackle, AbilityId::ThunderShock, AbilityId::TailWhip, AbilityId::ThunderWave, AbilityId::DoubleKick, AbilityId::Agility, AbilityId::PinMissile, AbilityId::Thunder, AbilityId::Bite, AbilityId::TakeDown, AbilityId::Flash, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::FocusEnergy, AbilityId::Growl} },
    { PkmnId::Flareon, { AbilityId::Ember, AbilityId::QuickAttack, AbilityId::SandAttack, AbilityId::Tackle, AbilityId::TailWhip, AbilityId::Bite, AbilityId::Leer, AbilityId::FireSpin, AbilityId::Rage, AbilityId::Flamethrower, AbilityId::TakeDown, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::Smog, AbilityId::FocusEnergy, AbilityId::Growl} },
    { PkmnId::Porygon, { AbilityId::Conversion, AbilityId::Sharpen, AbilityId::Tackle, AbilityId::Psybeam, AbilityId::Recover, AbilityId::Agility, AbilityId::TriAttack, AbilityId::Flash, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Psychic, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::Substitute} },
    { PkmnId::Omanyte, { AbilityId::WaterGun, AbilityId::Withdraw, AbilityId::HornAttack, AbilityId::Leer, AbilityId::SpikeCannon, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Omastar, { AbilityId::HornAttack, AbilityId::WaterGun, AbilityId::Withdraw, AbilityId::Leer, AbilityId::SpikeCannon, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Kabuto, { AbilityId::Harden, AbilityId::Scratch, AbilityId::Absorb, AbilityId::Slash, AbilityId::Leer, AbilityId::HydroPump, AbilityId::Surf, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Kabutops, { AbilityId::Absorb, AbilityId::Harden, AbilityId::Scratch, AbilityId::Slash, AbilityId::Leer, AbilityId::HydroPump, AbilityId::Surf, AbilityId::RazorWind, AbilityId::SwordsDance, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::Submission, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute, AbilityId::Cut} },
    { PkmnId::Aerodactyl, { AbilityId::Agility, AbilityId::WingAttack, AbilityId::Supersonic, AbilityId::Bite, AbilityId::TakeDown, AbilityId::HyperBeam, AbilityId::Fly, AbilityId::RazorWind, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::DoubleEdge, AbilityId::Rage, AbilityId::DragonRage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkyAttack, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Snorlax, { AbilityId::Amnesia, AbilityId::Headbutt, AbilityId::Rest, AbilityId::BodySlam, AbilityId::Harden, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Surf, AbilityId::Strength, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::PayDay, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::SolarBeam, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Psychic, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Metronome, AbilityId::SelfDestruct, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Psywave, AbilityId::RockSlide, AbilityId::Substitute} },
    { PkmnId::Articuno, { AbilityId::IceBeam, AbilityId::Peck, AbilityId::Blizzard, AbilityId::Agility, AbilityId::Mist, AbilityId::Fly, AbilityId::RazorWind, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::SkyAttack, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Zapdos, { AbilityId::DrillPeck, AbilityId::ThunderShock, AbilityId::Thunder, AbilityId::Agility, AbilityId::LightScreen, AbilityId::Fly, AbilityId::Flash, AbilityId::RazorWind, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Swift, AbilityId::SkyAttack, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Substitute} },
    { PkmnId::Moltres, { AbilityId::FireSpin, AbilityId::Peck, AbilityId::Leer, AbilityId::Agility, AbilityId::SkyAttack, AbilityId::Fly, AbilityId::RazorWind, AbilityId::Whirlwind, AbilityId::Toxic, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::HyperBeam, AbilityId::Rage, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Dratini, { AbilityId::Leer, AbilityId::Wrap, AbilityId::ThunderWave, AbilityId::Agility, AbilityId::Slam, AbilityId::DragonRage, AbilityId::HyperBeam, AbilityId::Surf, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Dragonair, { AbilityId::Leer, AbilityId::ThunderWave, AbilityId::Wrap, AbilityId::Agility, AbilityId::Slam, AbilityId::DragonRage, AbilityId::HyperBeam, AbilityId::Surf, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Dragonite, { AbilityId::Agility, AbilityId::Leer, AbilityId::ThunderWave, AbilityId::Wrap, AbilityId::Slam, AbilityId::DragonRage, AbilityId::HyperBeam, AbilityId::Surf, AbilityId::Strength, AbilityId::RazorWind, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::Rage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::Rest, AbilityId::Substitute} },
    { PkmnId::Mewtwo, { AbilityId::Confusion, AbilityId::Disable, AbilityId::Psychic, AbilityId::Swift, AbilityId::Barrier, AbilityId::Recover, AbilityId::Mist, AbilityId::Amnesia, AbilityId::Strength, AbilityId::Flash, AbilityId::MegaPunch, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::PayDay, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::SolarBeam, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::Metronome, AbilityId::SelfDestruct, AbilityId::FireBlast, AbilityId::SkullBash, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::TriAttack, AbilityId::Substitute} },
    { PkmnId::Mew, { AbilityId::Pound, AbilityId::Transform, AbilityId::MegaPunch, AbilityId::Metronome, AbilityId::Psychic, AbilityId::Cut, AbilityId::Fly, AbilityId::Surf, AbilityId::Strength, AbilityId::Flash, AbilityId::RazorWind, AbilityId::SwordsDance, AbilityId::Whirlwind, AbilityId::MegaKick, AbilityId::Toxic, AbilityId::HornDrill, AbilityId::BodySlam, AbilityId::TakeDown, AbilityId::DoubleEdge, AbilityId::BubbleBeam, AbilityId::WaterGun, AbilityId::IceBeam, AbilityId::Blizzard, AbilityId::HyperBeam, AbilityId::PayDay, AbilityId::Submission, AbilityId::Counter, AbilityId::SeismicToss, AbilityId::Rage, AbilityId::MegaDrain, AbilityId::SolarBeam, AbilityId::DragonRage, AbilityId::Thunderbolt, AbilityId::Thunder, AbilityId::Earthquake, AbilityId::Fissure, AbilityId::Dig, AbilityId::Teleport, AbilityId::Mimic, AbilityId::DoubleTeam, AbilityId::Reflect, AbilityId::Bide, AbilityId::SelfDestruct, AbilityId::EggBomb, AbilityId::FireBlast, AbilityId::Swift, AbilityId::SkullBash, AbilityId::SoftBoiled, AbilityId::DreamEater, AbilityId::SkyAttack, AbilityId::Rest, AbilityId::ThunderWave, AbilityId::Psywave, AbilityId::Explosion, AbilityId::RockSlide, AbilityId::TriAttack, AbilityId::Substitute} },
};
